### PR TITLE
feat: add working dockerfile and compose file

### LINKED ISSUE #2: Add Docker compose with better yaml settings
~~Expose Prometheus monitoring ports~~
Appropriate encryption on mqtt and postgres

### LINKED ISSUE #3: Create MQTT Broker Docker image
Based on official Docker image: https://hub.docker.com/_/eclipse-mosquitto

Incorporate Cedalo's Management UI https://github.com/cedalo/management-center

Netdata observability: https://learn.netdata.cloud/docs/collecting-metrics/message-brokers/mosquitto

### PR DESCRIPTION
**Pull request by vjFaLk**
- Change the Dockerfile to use the python:3.12-alpine image, also removed virtualenv stuff from container
- Added docker-compose file that connects with ActiveMQ Artemis and TimescaleDB
- Updated configuration yaml to take mqtt username and password 
- Add pyyaml to requirements (idk why it wasn't there)
- Changed psycopg to psycopg[binary] in requirements (this was needed to make it work in Docker)
- Remove virtualenv logic from `mqtt-pg-logger.sh`, but actually I'll leave that alone and put in the logic to start the python process in `entrypoint.sh` itself

### CODE REVIEW

**Comment by agritheory** [comment]
@vjFaLk Can we update the python version to 3.12? 3.8 just went EOL.

**Comment by Alchez** [comment]
@agritheory Merging this to move ahead, Valmik has given his blessings

**Comment by Alchez** [comment]
@agritheory Merging this to move ahead, valmik has given his blessings

**Comment by vjFaLk** [comment]
@agritheory I asked Rohan to merge this so that both Myuddin and Rohan aren't just working off my random branch. I'll raise a new PR cleaning this up. I'll make it so that by default the local setup doesn't use certs but there's configuration that can be uncommented / separate configuration for production setups where certs is mandatory.

**Pull request merged**
